/* ==========================================================================
   STAR ELECTRIC ENTERPRISES — catalogue adapter
   --------------------------------------------------------------------------
   Reads the imported, source-verified catalogue and exposes it to the
   storefront. All product data originates from the seven approved sources and
   is generated by the import pipeline into:

       data/catalogue-index.js     window.SEE_CATALOGUE  (all products, light)
       data/products/<source>.js   window.SEE_DETAIL     (full record, on demand)

   Nothing in this file invents product information. Where a source does not
   publish a value the catalogue carries null / "Not specified" / "Request
   Quote" and the UI must render that honestly - never Rs. 0, never a made-up
   rating, never an unearned "Best Seller" badge.

   On WordPress this file disappears: the index becomes a WooCommerce product
   loop and the detail lookup becomes single-product data.
   ========================================================================== */
window.SEE_DATA = (function () {
  "use strict";

  var C = window.SEE_CATALOGUE || { products: [], categories: [], brands: [] };
  var IMG_FALLBACK = "assets/images/products/";

  /* ---------------------------------------------------------------- images */
  /* These line-art keys are CATEGORY icons - used for category tiles and
     navigation only. They are never used as a product photograph: a product
     either shows the real image published by its own source, or it shows an
     honest "Product image unavailable" state. */
  var CATEGORY_ICON = {
    "wires-cables": "cable-coil",
    "switches-sockets": "switch-plate",
    "circuit-protection": "mcb",
    "industrial-control": "relay",
    "fans-ventilation": "ceiling-fan",
    "lighting": "led-bulb",
    "power-energy": "energy-meter",
    "smart-home": "smart-plug",
    "electrical-accessories": "tape"
  };
  var PHOTO = ["flex-cable", "flex-cable-alt", "cable-gland", "connector", "switch-plate",
    "socket", "mcb", "mcb-alt", "distribution-box", "fuse", "changeover", "relay",
    "led-bulb", "floodlight", "ceiling-fan", "exhaust-fan", "energy-meter", "smart-plug",
    "tester", "drill", "drill-alt", "tape", "tape-alt", "extension-board",
    "extension-board-alt"];

  function imageUrl(key) {
    if (!key) { return null; }
    if (/^(assets\/|https?:)/.test(key)) { return key; }
    return IMG_FALLBACK + key + (PHOTO.indexOf(key) !== -1 ? ".webp" : ".svg");
  }
  function categoryImage(slug) { return "assets/images/categories/" + slug + ".webp"; }
  function hasPhoto(key) { return PHOTO.indexOf(key) !== -1; }

  /* Product imagery is source-verified or absent. No category icon, stock
     photograph, generated render or substitute from another retailer is ever
     shown in place of a product's own image. Callers must handle null by
     rendering the "Product image unavailable" state. */
  function productImage(p) {
    return p && p.img ? imageUrl(p.img) : null;
  }

  /* ------------------------------------------------------- stock + pricing */
  function stockCode(availability) {
    if (availability === "In Stock") { return "in"; }
    if (availability === "Out of Stock") { return "out"; }
    return "unknown";               // "Not specified" - never guessed
  }

  /* Adapt an index record to the shape the existing components expect.
     Deliberately NO rating and NO review count: no source publishes them and
     inventing them is forbidden. */
  function adapt(x) {
    return {
      id: x.id,
      slug: x.slug,
      name: x.name,
      brand: x.brand,
      model: x.model,
      sku: x.sku,
      cat: x.category,
      sub: x.subcategory,
      series: x.series,
      price: x.price,
      oldPrice: x.regularPrice,
      discountPercent: x.discountPercent,
      priceType: x.priceType,
      isQuote: x.priceType === "quote" || x.price === null,
      stock: stockCode(x.availability),
      availability: x.availability,
      img: x.img,
      imgType: x.imgType || null,
      /* Department memberships. A product belongs to one category but can
         sit in several departments - a Wi-Fi switch is Smart Switches,
         Home Automation and Office Automation Solutions at once - without
         a second record existing anywhere. */
      depts: x.depts || [],
      type: x.hasVariations ? "variable" : "simple",
      tags: buildTags(x),
      sourceDomain: x.source,
      specText: x.spec || "",
      short: ""
    };
  }

  /* Tags are derived from facts, never asserted. "deal" requires a real
     source discount; there is no "best seller" because no source ranks sales. */
  function buildTags(x) {
    var t = [];
    if (x.discountPercent) { t.push("deal"); }
    if (x.priceType === "quote") { t.push("quote"); }
    return t;
  }

  var PRODUCTS = (C.products || []).map(adapt);
  var BY_ID = {};
  var BY_SLUG = {};
  for (var i = 0; i < PRODUCTS.length; i++) {
    BY_ID[PRODUCTS[i].id] = PRODUCTS[i];
    BY_SLUG[PRODUCTS[i].slug] = PRODUCTS[i];
  }

  /* ------------------------------------------------------------ categories */
  var CATEGORIES = (C.categories || []).map(function (c) {
    return {
      slug: c.slug,
      name: c.name,
      blurb: c.blurb || "",
      count: c.count,
      icon: CATEGORY_ICON[c.slug] || "cable-coil",
      subs: (c.subcategories || []).map(function (s) {
        return { slug: s.slug, name: s.name, count: s.count,
                 icon: CATEGORY_ICON[c.slug] || "cable-coil" };
      })
    };
  });

  var BRANDS = (C.brands || []).map(function (b) {
    return { slug: b.slug, name: b.name, mark: b.mark,
             count: b.productCount != null ? b.productCount : (b.count || 0),
             familyCount: b.familyCount || 0,
             catalogueExposed: b.catalogueExposed !== false,
             sourceDomains: b.sourceDomains || [], note: b.note || "" };
  });

  /* ------------------------------------------------------------- families
     Product families and series are NOT products and are never rendered as
     product cards. A family is a group name the source publishes without any
     item-level model, specification, image or price behind it, so it is used
     only for navigation: brand pages, category pages and enquiries.
     data/families.js is optional - pages that need it load it explicitly. */
  var F = window.SEE_FAMILIES || { families: [] };
  var FAMILIES = (F.families || []).slice();

  function familiesForBrand(slug) {
    return FAMILIES.filter(function (f) { return f.brandSlug === slug; });
  }
  function familiesForCategory(slug) {
    return FAMILIES.filter(function (f) { return f.category === slug; });
  }
  function familiesForDepartment(slug) {
    return FAMILIES.filter(function (f) {
      return (f.depts || []).indexOf(slug) !== -1;
    });
  }
  function familyById(id) {
    for (var i = 0; i < FAMILIES.length; i++) {
      if (FAMILIES[i].id === id) { return FAMILIES[i]; }
    }
    return null;
  }


  /* ==================================================================
     HOMEPAGE MERCHANDISING
     ------------------------------------------------------------------
     The homepage groups the catalogue into shopper-facing departments.
     Every entry resolves to a real filter over verified products - there
     is no merchandising label here that the catalogue cannot back, and
     nothing is duplicated just because a name could be written two ways.

     Labels the business has not established are deliberately absent:
     earthing material and networking hardware are not in the catalogue,
     and no automation service has been confirmed, so none is advertised.
     ================================================================== */

  /* Select products for a homepage rail. `sel` is a plain filter, so the
     same definition drives both the tile and the link it opens. */
  function selectProducts(sel, limit) {
    sel = sel || {};
    var words = (sel.query || "").toLowerCase().split(/\s+/).filter(Boolean);
    var out = [];
    for (var i = 0; i < PRODUCTS.length; i++) {
      var p = PRODUCTS[i];
      if (sel.dept && p.depts.indexOf(sel.dept) === -1) { continue; }
      if (sel.cat && p.cat !== sel.cat) { continue; }
      if (sel.sub && p.sub !== sel.sub) { continue; }
      if (sel.brand && p.brand !== sel.brand) { continue; }
      if (words.length) {
        var hay = [p.name, p.model, p.sku, p.brand, p.series, p.sub, p.specText]
                    .join(" ").toLowerCase();
        var ok = true;
        for (var w = 0; w < words.length; w++) {
          if (hay.indexOf(words[w]) === -1) { ok = false; break; }
        }
        if (!ok) { continue; }
      }
      out.push(p);
    }
    /* Lead with what a shopper can act on: a published price, in stock and
       a photograph of the item itself. This is a display order, not a claim. */
    out.sort(function (a, b) {
      return (score(b) - score(a));
    });
    return limit ? out.slice(0, limit) : out;
  }
  function score(p) {
    var n = 0;
    if (p.price !== null) { n += 4; }
    if (p.stock === "in") { n += 2; }
    if (p.imgType === "exact-image") { n += 2; }
    if (p.discountPercent) { n += 1; }
    return n;
  }

  /* A homepage row should look like its department. Taking the highest
     scoring products alone would fill "Wires & Cables" with the handful of
     priced conduit boxes and never show a cable, so a rail takes the best
     from each subcategory in turn. */
  function spreadProducts(sel, limit) {
    sel = sel || {};
    var all = selectProducts(sel);
    if (!sel.cat || sel.sub || sel.query || all.length <= limit) {
      return all.slice(0, limit);
    }
    var groups = {}, order = [];
    for (var i = 0; i < all.length; i++) {
      var k = all[i].sub || "_";
      if (!groups[k]) { groups[k] = []; order.push(k); }
      groups[k].push(all[i]);
    }
    /* Biggest subcategories lead, then one from each in rotation. */
    order.sort(function (a, b) { return groups[b].length - groups[a].length; });
    var out = [], round = 0;
    while (out.length < limit) {
      var added = false;
      for (var g = 0; g < order.length && out.length < limit; g++) {
        var list = groups[order[g]];
        if (round < list.length) { out.push(list[round]); added = true; }
      }
      if (!added) { break; }
      round++;
    }
    return out;
  }

  /* Where a rail sends the shopper. Kept next to the filter so the two
     can never drift apart. */
  function selectionUrl(sel) {
    sel = sel || {};
    if (sel.dept) {
      return "category.html?dept=" + encodeURIComponent(sel.dept);
    }
    if (sel.query) {
      return "search-results.html?s=" + encodeURIComponent(sel.query) +
             (sel.cat ? "&product_cat=" + encodeURIComponent(sel.cat) : "");
    }
    if (sel.cat) {
      return "category.html?cat=" + encodeURIComponent(sel.cat) +
             (sel.sub ? "&sub=" + encodeURIComponent(sel.sub) : "");
    }
    return "shop.html";
  }

  /* Departments shown as the circular strip and in the hero rail.
     `label` is what the shopper reads; `sel` is what it actually filters. */
  var DEPARTMENTS = [
    { label: "Wires & Cables",        sel: { cat: "wires-cables" }, art: "wires-cables" },
    { label: "Power Cables",          sel: { cat: "wires-cables", sub: "power-cables" }, art: "power-cables" },
    { label: "Solar Panel Cables",    sel: { cat: "wires-cables", sub: "solar-cables" }, art: "solar-cables" },
    { label: "PVC Pipe & Conduit",    sel: { cat: "wires-cables", sub: "cable-management" }, art: "pvc-conduit" },
    { label: "Switches & Sockets",    sel: { cat: "switches-sockets" }, art: "switches-sockets" },
    { label: "Smart Switches",        sel: { cat: "smart-home", sub: "smart-switches" }, art: "smart-switches" },
    { label: "Data & Telephone Outlets", sel: { cat: "switches-sockets", query: "data socket" }, art: "data-outlets" },
    { label: "Circuit Protection",    sel: { cat: "circuit-protection" }, art: "circuit-protection" },
    { label: "Distribution Boards",   sel: { cat: "electrical-accessories", sub: "distribution-boards" }, art: "distribution-boards" },
    { label: "Lighting & Fixtures",   sel: { cat: "lighting" }, art: "lighting" },
    { label: "LED Lighting",          sel: { cat: "lighting", sub: "led-lighting" }, art: "led-lighting" },
    { label: "Fans & Ventilation",    sel: { cat: "fans-ventilation" }, art: "fans-ventilation" },
    { label: "Wiring Accessories",    sel: { cat: "electrical-accessories" }, art: "wiring-accessories" },
    { label: "Smart Home",            sel: { cat: "smart-home" }, art: "smart-home" },
    { label: "Industrial Control",    sel: { cat: "industrial-control" }, art: "industrial-control" },
    { label: "Power & Energy",        sel: { cat: "power-energy" }, art: "power-energy" },
    { label: "Earthing Material",     sel: { cat: "earthing-material" }, art: "earthing-material" },
    { label: "Networking Solutions",  sel: { dept: "networking-solutions" }, art: "networking-solutions" },
    { label: "Home Automation",       sel: { dept: "home-automation" }, art: "home-automation" },
    { label: "Office Automation Solutions", sel: { dept: "office-automation" }, art: "office-automation" }
  ];

  /* Product rails on the homepage. Only departments with enough individual
     products to fill a row appear here; Industrial Control and Power &
     Energy are published by their sources at range level only, so they stay
     in the departments strip and on their category pages instead. */
  var HOME_RAILS = [
    { title: "Wires & Cables",        sel: { cat: "wires-cables" } },
    { title: "Switches & Sockets",    sel: { cat: "switches-sockets" } },
    { title: "Lighting & Fixtures",   sel: { cat: "lighting" } },
    { title: "Fans & Ventilation",    sel: { cat: "fans-ventilation" } },
    { title: "Circuit Protection",    sel: { cat: "circuit-protection" } },
    { title: "Wiring Accessories",    sel: { cat: "electrical-accessories" } },
    { title: "Solar Panel Cables",    sel: { cat: "wires-cables", sub: "solar-cables" } },
    { title: "Home Automation",       sel: { dept: "home-automation" } },
    { title: "Office Automation Solutions", sel: { dept: "office-automation" } },
    { title: "Networking Solutions",  sel: { dept: "networking-solutions" } }
  ];

  /* A department's picture is a real photograph of something inside it:
     the first product image, or the range image where a source publishes
     ranges only. Never an icon standing in for a product. */
  /* Every department shows the same kind of picture: the product photograph on
     a white stage, at a common subject scale, generated once into
     assets/images/departments/. That is what keeps the strip looking like one
     set rather than a mix of studio backdrops and cut-outs. */
  function departmentImage(dep) {
    if (dep.art) { return "assets/images/departments/" + dep.art + ".webp"; }
    var first = selectProducts(dep.sel, 1)[0];
    if (first && first.img) { return imageUrl(first.img); }
    var fam = familiesForCategory(dep.sel.cat)[0];
    if (fam && fam.img) { return imageUrl(fam.img); }
    return categoryImage(dep.sel.cat);
  }

  /* The left-hand rail: the real category tree, plus the shortcuts shoppers
     ask for by name. Every entry points at a filter that returns products. */
  var RAIL_SHORTCUTS = [
    { label: "Solar Panel Cables",       sel: { cat: "wires-cables", sub: "solar-cables" } },
    { label: "PVC Pipe & Conduit",       sel: { cat: "wires-cables", sub: "cable-management" } },
    { label: "Distribution Boards",      sel: { cat: "electrical-accessories", sub: "distribution-boards" } },
    { label: "LED Lighting",             sel: { cat: "lighting", sub: "led-lighting" } },
    { label: "Smart Switches",           sel: { cat: "smart-home", sub: "smart-switches" } },
    { label: "Data & Telephone Outlets", sel: { cat: "switches-sockets", query: "data socket" } },
    { label: "Earthing Material",        sel: { cat: "earthing-material" } },
    { label: "Networking Solutions",     sel: { dept: "networking-solutions" } },
    { label: "Home Automation",          sel: { dept: "home-automation" } },
    { label: "Office Automation Solutions", sel: { dept: "office-automation" } }
  ];

  function railSections() {
    var out = CATEGORIES.map(function (c) {
      return {
        label: c.name, href: "category.html?cat=" + encodeURIComponent(c.slug),
        count: c.count,
        subs: (c.subs || []).map(function (s) {
          return { name: s.name, count: s.count,
                   href: "category.html?cat=" + encodeURIComponent(c.slug) +
                         "&sub=" + encodeURIComponent(s.slug) };
        })
      };
    });
    RAIL_SHORTCUTS.forEach(function (d) {
      var n = selectProducts(d.sel).length;
      if (!n && d.sel.cat) { n = familiesForCategory(d.sel.cat).length; }
      out.push({ label: d.label, href: selectionUrl(d.sel), count: n, subs: [] });
    });
    return out;
  }

  var DEPT_BLURB = {
    "earthing-material": "Earthing, structural lightning protection and surge protection ranges from ABB Furse.",
    "networking-solutions": "Structured data cabling from the Pakistan Cables networking catalogue.",
    "home-automation": "Wi-Fi switches, controls, motors and smart devices for the home.",
    "office-automation": "The same verified smart control products, grouped for workplace use. " +
                         "These are products we list; no installation or automation service is offered."
  };

  function departmentBySlug(slug) {
    var all = departments();
    for (var i = 0; i < all.length; i++) {
      var key = all[i].sel.dept || all[i].sel.cat;
      if (key === slug) {
        all[i].blurb = DEPT_BLURB[slug] || "";
        return all[i];
      }
    }
    return null;
  }

  /* Readable department names, used so a search for "home automation" matches. */
  function departmentName(list) {
    if (!list || !list.length) { return ""; }
    var out = [];
    for (var i = 0; i < DEPARTMENTS.length; i++) {
      var key = DEPARTMENTS[i].sel.dept || DEPARTMENTS[i].sel.cat;
      if (list.indexOf(key) !== -1) { out.push(DEPARTMENTS[i].label); }
    }
    return out.join(" ");
  }

  function departments() {
    return DEPARTMENTS.map(function (d) {
      var n = selectProducts(d.sel).length;
      var fams = d.sel.dept ? familiesForDepartment(d.sel.dept)
                            : familiesForCategory(d.sel.cat);
      return {
        label: d.label, sel: d.sel, count: n, art: d.art,
        familyCount: n ? 0 : fams.length,
        href: selectionUrl(d.sel), img: departmentImage(d)
      };
    });
  }

  /* ------------------------------------------------------------- lookups */
  function categoryBySlug(s) {
    for (var i = 0; i < CATEGORIES.length; i++) {
      if (CATEGORIES[i].slug === s) { return CATEGORIES[i]; }
    }
    return null;
  }
  function categoryName(s) { var c = categoryBySlug(s); return c ? c.name : s || ""; }
  function brandBySlug(s) {
    for (var i = 0; i < BRANDS.length; i++) {
      if (BRANDS[i].slug === s) { return BRANDS[i]; }
    }
    return null;
  }
  function brandName(s) { var b = brandBySlug(s); return b ? b.name : s || ""; }
  function productById(id) { return BY_ID[id] || null; }
  function productBySlug(s) { return BY_SLUG[s] || null; }

  function byTag(tag, limit) {
    var out = PRODUCTS.filter(function (p) { return p.tags.indexOf(tag) !== -1; });
    return limit ? out.slice(0, limit) : out;
  }

  /* Homepage subsets are selections from the real catalogue, not claims.
     "featured" = priced, in stock, has a photograph - a display choice.
     "deals"    = genuine source discount only. */
  /* Prefer products the source prices and stocks; fall back to any priced
     product so the homepage is populated from real data either way. */
  function featured(limit) {
    var out = PRODUCTS.filter(function (p) {
      return p.price !== null && p.stock === "in";
    });
    if (out.length < (limit || 8)) {
      out = out.concat(PRODUCTS.filter(function (p) {
        return p.price !== null && out.indexOf(p) === -1; }));
    }
    return limit ? out.slice(0, limit) : out;
  }
  function withPhotos(limit) {
    var out = PRODUCTS.filter(function (p) { return !!p.img; });
    if (out.length < (limit || 8)) {
      out = out.concat(PRODUCTS.filter(function (p) {
        return p.price !== null && out.indexOf(p) === -1; }));
    }
    return limit ? out.slice(0, limit) : out;
  }
  function deals(limit) {
    var out = PRODUCTS.filter(function (p) { return p.discountPercent; })
                      .sort(function (a, b) { return b.discountPercent - a.discountPercent; });
    return limit ? out.slice(0, limit) : out;
  }

  /* ------------------------------------------- full detail, loaded on demand
     A dynamic <script> is used rather than fetch() so the prototype still works
     when opened directly from disk. */
  var SOURCE_OF_PREFIX = {
    "pc": "pakistan-cables", "aqua": "aqua-electrical", "wahid": "wahid-fans",
    "et": "electro-traders", "himel": "himel", "hyundai": "hyundai",
    "coarts": "coarts-lighting"
  };

  function sourceFileFor(id) {
    var pre = String(id || "").split("-")[0];
    return SOURCE_OF_PREFIX[pre] || null;
  }

  function loadDetail(id, cb) {
    var file = sourceFileFor(id);
    if (!file) { cb(null); return; }
    window.SEE_DETAIL = window.SEE_DETAIL || {};
    if (window.SEE_DETAIL[file]) { cb(window.SEE_DETAIL[file][id] || null); return; }
    var s = document.createElement("script");
    s.src = "data/products/" + file + ".js";
    s.onload = function () {
      cb((window.SEE_DETAIL[file] || {})[id] || null);
    };
    s.onerror = function () { cb(null); };
    document.head.appendChild(s);
  }

  return {
    IMG: IMG_FALLBACK,
    CATEGORIES: CATEGORIES,
    BRANDS: BRANDS,
    FAMILIES: FAMILIES,
    familiesForBrand: familiesForBrand,
    familiesForCategory: familiesForCategory,
    familiesForDepartment: familiesForDepartment,
    familyById: familyById,
    PRODUCTS: PRODUCTS,
    generatedAt: C.generatedAt || null,
    categoryBySlug: categoryBySlug,
    categoryName: categoryName,
    brandBySlug: brandBySlug,
    brandName: brandName,
    productById: productById,
    productBySlug: productBySlug,
    byTag: byTag,
    featured: featured,
    withPhotos: withPhotos,
    deals: deals,
    imageUrl: imageUrl,
    productImage: productImage,
    categoryImage: categoryImage,
    hasPhoto: hasPhoto,
    loadDetail: loadDetail,
    sourceFileFor: sourceFileFor,
    selectProducts: selectProducts,
    spreadProducts: spreadProducts,
    selectionUrl: selectionUrl,
    departments: departments,
    departmentBySlug: departmentBySlug,
    departmentName: departmentName,
    railSections: railSections,
    HOME_RAILS: HOME_RAILS
  };
})();
