/* ==========================================================================
   STAR ELECTRIC ENTERPRISES — catalogue adapter
   --------------------------------------------------------------------------
   Reads the imported, source-verified catalogue and exposes it to the
   storefront. All product data originates from the seven approved sources and
   is generated by the import pipeline into:

       data/catalogue-index.js     window.SEE_CATALOGUE  (all products, light)
       data/products/<source>.js   window.SEE_DETAIL     (full record, on demand)

   Nothing in this file invents product information. Where a source does not
   publish a value the catalogue carries null / "Not specified" / "Request
   Quote" and the UI must render that honestly - never Rs. 0, never a made-up
   rating, never an unearned "Best Seller" badge.

   On WordPress this file disappears: the index becomes a WooCommerce product
   loop and the detail lookup becomes single-product data.
   ========================================================================== */
window.SEE_DATA = (function () {
  "use strict";

  var C = window.SEE_CATALOGUE || { products: [], categories: [], brands: [] };
  var IMG_FALLBACK = "assets/images/products/";

  /* ---------------------------------------------------------------- images */
  /* These line-art keys are CATEGORY icons - used for category tiles and
     navigation only. They are never used as a product photograph: a product
     either shows the real image published by its own source, or it shows an
     honest "Product image unavailable" state. */
  var CATEGORY_ICON = {
    "wires-cables": "cable-coil",
    "switches-sockets": "switch-plate",
    "circuit-protection": "mcb",
    "industrial-control": "relay",
    "fans-ventilation": "ceiling-fan",
    "lighting": "led-bulb",
    "power-energy": "energy-meter",
    "smart-home": "smart-plug",
    "electrical-accessories": "tape"
  };
  var PHOTO = ["flex-cable", "flex-cable-alt", "cable-gland", "connector", "switch-plate",
    "socket", "mcb", "mcb-alt", "distribution-box", "fuse", "changeover", "relay",
    "led-bulb", "floodlight", "ceiling-fan", "exhaust-fan", "energy-meter", "smart-plug",
    "tester", "drill", "drill-alt", "tape", "tape-alt", "extension-board",
    "extension-board-alt"];

  function imageUrl(key) {
    if (!key) { return null; }
    if (/^(assets\/|https?:)/.test(key)) { return key; }
    return IMG_FALLBACK + key + (PHOTO.indexOf(key) !== -1 ? ".webp" : ".svg");
  }
  function categoryImage(slug) { return "assets/images/categories/" + slug + ".webp"; }
  function hasPhoto(key) { return PHOTO.indexOf(key) !== -1; }

  /* Product imagery is source-verified or absent. No category icon, stock
     photograph, generated render or substitute from another retailer is ever
     shown in place of a product's own image. Callers must handle null by
     rendering the "Product image unavailable" state. */
  function productImage(p) {
    return p && p.img ? imageUrl(p.img) : null;
  }

  /* ------------------------------------------------------- stock + pricing */
  function stockCode(availability) {
    if (availability === "In Stock") { return "in"; }
    if (availability === "Out of Stock") { return "out"; }
    return "unknown";               // "Not specified" - never guessed
  }

  /* Adapt an index record to the shape the existing components expect.
     Deliberately NO rating and NO review count: no source publishes them and
     inventing them is forbidden. */
  function adapt(x) {
    return {
      id: x.id,
      slug: x.slug,
      name: x.name,
      brand: x.brand,
      model: x.model,
      sku: x.sku,
      cat: x.category,
      sub: x.subcategory,
      series: x.series,
      price: x.price,
      oldPrice: x.regularPrice,
      discountPercent: x.discountPercent,
      priceType: x.priceType,
      isQuote: x.priceType === "quote" || x.price === null,
      stock: stockCode(x.availability),
      availability: x.availability,
      img: x.img,
      type: x.hasVariations ? "variable" : "simple",
      tags: buildTags(x),
      sourceDomain: x.source,
      specText: x.spec || "",
      short: ""
    };
  }

  /* Tags are derived from facts, never asserted. "deal" requires a real
     source discount; there is no "best seller" because no source ranks sales. */
  function buildTags(x) {
    var t = [];
    if (x.discountPercent) { t.push("deal"); }
    if (x.priceType === "quote") { t.push("quote"); }
    return t;
  }

  var PRODUCTS = (C.products || []).map(adapt);
  var BY_ID = {};
  var BY_SLUG = {};
  for (var i = 0; i < PRODUCTS.length; i++) {
    BY_ID[PRODUCTS[i].id] = PRODUCTS[i];
    BY_SLUG[PRODUCTS[i].slug] = PRODUCTS[i];
  }

  /* ------------------------------------------------------------ categories */
  var CATEGORIES = (C.categories || []).map(function (c) {
    return {
      slug: c.slug,
      name: c.name,
      blurb: c.blurb || "",
      count: c.count,
      icon: CATEGORY_ICON[c.slug] || "cable-coil",
      subs: (c.subcategories || []).map(function (s) {
        return { slug: s.slug, name: s.name, count: s.count,
                 icon: CATEGORY_ICON[c.slug] || "cable-coil" };
      })
    };
  });

  var BRANDS = (C.brands || []).map(function (b) {
    return { slug: b.slug, name: b.name, mark: b.mark,
             count: b.productCount != null ? b.productCount : (b.count || 0),
             familyCount: b.familyCount || 0,
             catalogueExposed: b.catalogueExposed !== false,
             sourceDomains: b.sourceDomains || [], note: b.note || "" };
  });

  /* ------------------------------------------------------------- families
     Product families and series are NOT products and are never rendered as
     product cards. A family is a group name the source publishes without any
     item-level model, specification, image or price behind it, so it is used
     only for navigation: brand pages, category pages and enquiries.
     data/families.js is optional - pages that need it load it explicitly. */
  var F = window.SEE_FAMILIES || { families: [] };
  var FAMILIES = (F.families || []).slice();

  function familiesForBrand(slug) {
    return FAMILIES.filter(function (f) { return f.brandSlug === slug; });
  }
  function familiesForCategory(slug) {
    return FAMILIES.filter(function (f) { return f.category === slug; });
  }
  function familyById(id) {
    for (var i = 0; i < FAMILIES.length; i++) {
      if (FAMILIES[i].id === id) { return FAMILIES[i]; }
    }
    return null;
  }

  /* ------------------------------------------------------------- lookups */
  function categoryBySlug(s) {
    for (var i = 0; i < CATEGORIES.length; i++) {
      if (CATEGORIES[i].slug === s) { return CATEGORIES[i]; }
    }
    return null;
  }
  function categoryName(s) { var c = categoryBySlug(s); return c ? c.name : s || ""; }
  function brandBySlug(s) {
    for (var i = 0; i < BRANDS.length; i++) {
      if (BRANDS[i].slug === s) { return BRANDS[i]; }
    }
    return null;
  }
  function brandName(s) { var b = brandBySlug(s); return b ? b.name : s || ""; }
  function productById(id) { return BY_ID[id] || null; }
  function productBySlug(s) { return BY_SLUG[s] || null; }

  function byTag(tag, limit) {
    var out = PRODUCTS.filter(function (p) { return p.tags.indexOf(tag) !== -1; });
    return limit ? out.slice(0, limit) : out;
  }

  /* Homepage subsets are selections from the real catalogue, not claims.
     "featured" = priced, in stock, has a photograph - a display choice.
     "deals"    = genuine source discount only. */
  /* Prefer products the source prices and stocks; fall back to any priced
     product so the homepage is populated from real data either way. */
  function featured(limit) {
    var out = PRODUCTS.filter(function (p) {
      return p.price !== null && p.stock === "in";
    });
    if (out.length < (limit || 8)) {
      out = out.concat(PRODUCTS.filter(function (p) {
        return p.price !== null && out.indexOf(p) === -1; }));
    }
    return limit ? out.slice(0, limit) : out;
  }
  function withPhotos(limit) {
    var out = PRODUCTS.filter(function (p) { return !!p.img; });
    if (out.length < (limit || 8)) {
      out = out.concat(PRODUCTS.filter(function (p) {
        return p.price !== null && out.indexOf(p) === -1; }));
    }
    return limit ? out.slice(0, limit) : out;
  }
  function deals(limit) {
    var out = PRODUCTS.filter(function (p) { return p.discountPercent; })
                      .sort(function (a, b) { return b.discountPercent - a.discountPercent; });
    return limit ? out.slice(0, limit) : out;
  }

  /* ------------------------------------------- full detail, loaded on demand
     A dynamic <script> is used rather than fetch() so the prototype still works
     when opened directly from disk. */
  var SOURCE_OF_PREFIX = {
    "pc": "pakistan-cables", "aqua": "aqua-electrical", "wahid": "wahid-fans",
    "et": "electro-traders", "himel": "himel", "hyundai": "hyundai",
    "coarts": "coarts-lighting"
  };

  function sourceFileFor(id) {
    var pre = String(id || "").split("-")[0];
    return SOURCE_OF_PREFIX[pre] || null;
  }

  function loadDetail(id, cb) {
    var file = sourceFileFor(id);
    if (!file) { cb(null); return; }
    window.SEE_DETAIL = window.SEE_DETAIL || {};
    if (window.SEE_DETAIL[file]) { cb(window.SEE_DETAIL[file][id] || null); return; }
    var s = document.createElement("script");
    s.src = "data/products/" + file + ".js";
    s.onload = function () {
      cb((window.SEE_DETAIL[file] || {})[id] || null);
    };
    s.onerror = function () { cb(null); };
    document.head.appendChild(s);
  }

  return {
    IMG: IMG_FALLBACK,
    CATEGORIES: CATEGORIES,
    BRANDS: BRANDS,
    FAMILIES: FAMILIES,
    familiesForBrand: familiesForBrand,
    familiesForCategory: familiesForCategory,
    familyById: familyById,
    PRODUCTS: PRODUCTS,
    generatedAt: C.generatedAt || null,
    categoryBySlug: categoryBySlug,
    categoryName: categoryName,
    brandBySlug: brandBySlug,
    brandName: brandName,
    productById: productById,
    productBySlug: productBySlug,
    byTag: byTag,
    featured: featured,
    withPhotos: withPhotos,
    deals: deals,
    imageUrl: imageUrl,
    productImage: productImage,
    categoryImage: categoryImage,
    hasPhoto: hasPhoto,
    loadDetail: loadDetail,
    sourceFileFor: sourceFileFor
  };
})();
